In [2]:
import pandas as pd

# Year 2021

In [3]:
drop21 = pd.read_csv('drop21.csv')

# re-compute schoolcode to be consistent with other dataset
drop21['SchoolCode'] = drop21['SchoolCode'].astype('str')

for i in range(drop21.shape[0]):
    code_len = len(drop21.loc[i, 'SchoolCode'])
    if code_len != 7:
        add_len = 7 - code_len
        add_str = '0' * add_len
        drop21.loc[i, 'SchoolCode'] = add_str + drop21.loc[i, 'SchoolCode']

# compute cdc_code
drop21[['CountyCode','DistrictCode','SchoolCode']] = drop21[['CountyCode','DistrictCode',
                                                             'SchoolCode']].astype('str')
drop21['cdc_code'] = drop21['CountyCode'] + drop21['DistrictCode'] + drop21['SchoolCode']

# remove rows with no dropout data
drop21 = drop21.loc[drop21['Dropout (Rate)'] != '*']
drop21 = drop21.drop(columns = ['AcademicYear', 'AggregateLevel'])
dropout21 = drop21.loc[drop21['ReportingCategory'] == 'TA'].drop(columns = ['ReportingCategory', 
                                                                            'Dropout (Count)'])

In [101]:
demo21 = drop21.loc[:, ['cdc_code', 'ReportingCategory', 'CohortStudents']].pivot(index = 'cdc_code', 
                    columns = 'ReportingCategory', values = 'CohortStudents').fillna(0).reset_index()

demo21 = demo21.loc[:, ['cdc_code', 'RW', 'RB', 'RH', 'SS', 'TA']]
demo21.loc[:, ['RW', 'RB', 'RH', 'SS', 'TA']] = demo21.loc[:, ['RW', 'RB', 'RH', 'SS', 'TA']].astype('int')

demo21['white'] = demo21['RW'] / demo21['TA']
demo21['black'] = demo21['RB'] / demo21['TA']
demo21['hispanic'] = demo21['RH'] / demo21['TA']
demo21['lowincome'] = demo21['SS'] / demo21['TA']

demo21 = demo21.loc[:, ['cdc_code', 'white', 'black', 'hispanic', 'lowincome']]

demo21['white'] = demo21.white.astype('float')
demo21['black'] = demo21.black.astype('float')
demo21['hispanic'] = demo21.hispanic.astype('float')
demo21['lowincome'] = demo21.lowincome.astype('float')

dropout_21 = demo21.merge(dropout21, on = 'cdc_code').rename(columns = {'CountyCode':'countycode', 'DistrictCode':
                                                          'districtcode', 'SchoolCode':'schoolcode',
                                                           'CountyName':'county',
                                                          'DistrictName':'district', 'SchoolName':'school',
                                                          'CohortStudents':'totalenrolled',
                                                          'Dropout (Rate)':'dropout'})

dropout_21['year'] = 2021

dropout_21.to_csv('cali_drop21.csv')

# Year 2019

In [105]:
drop19 = pd.read_csv('drop19.csv')

# re-compute schoolcode to be consistent with other dataset
drop19['SchoolCode'] = drop19['SchoolCode'].astype('str')
for i in range(drop19.shape[0]):
    code_len = len(drop19.loc[i, 'SchoolCode'])
    if code_len != 7:
        add_len = 7 - code_len
        add_str = '0' * add_len
        drop19.loc[i, 'SchoolCode'] = add_str + drop19.loc[i, 'SchoolCode']

# compute cdc_code
drop19[['CountyCode','DistrictCode','SchoolCode']] = drop19[['CountyCode','DistrictCode',
                                                             'SchoolCode']].astype('str')

drop19['cdc_code'] = drop19['CountyCode'] + drop19['DistrictCode'] + drop19['SchoolCode']

# remove rows with no dropout data
drop19 = drop19.loc[drop19['Dropout (Rate)'] != '*']
drop19 = drop19.drop(columns = ['AcademicYear', 'AggregateLevel'])
dropout19 = drop19.loc[drop19['ReportingCategory'] == 'TA'].drop(columns = ['ReportingCategory', 
                                                                            'Dropout (Count)'])

In [106]:
demo19 = drop19.loc[:, ['cdc_code', 'ReportingCategory', 'CohortStudents']].pivot(index = 'cdc_code', 
                    columns = 'ReportingCategory', values = 'CohortStudents').fillna(0).reset_index()

demo19 = demo19.loc[:, ['cdc_code', 'RW', 'RB', 'RH', 'SS', 'TA']]
demo19.loc[:, ['RW', 'RB', 'RH', 'SS', 'TA']] = demo19.loc[:, ['RW', 'RB', 'RH', 'SS', 'TA']].astype('int')

demo19['white'] = demo19['RW'] / demo19['TA']
demo19['black'] = demo19['RB'] / demo19['TA']
demo19['hispanic'] = demo19['RH'] / demo19['TA']
demo19['lowincome'] = demo19['SS'] / demo19['TA']

demo19 = demo19.loc[:, ['cdc_code', 'white', 'black', 'hispanic', 'lowincome']]

demo19['white'] = demo19.white.astype('float')
demo19['black'] = demo19.black.astype('float')
demo19['hispanic'] = demo19.hispanic.astype('float')
demo19['lowincome'] = demo19.lowincome.astype('float')

dropout_19 = demo19.merge(dropout19, on = 'cdc_code').rename(columns = {'CountyCode':'countycode', 'DistrictCode':
                                                          'districtcode', 'SchoolCode':'schoolcode',
                                                           'CountyName':'county',
                                                          'DistrictName':'district', 'SchoolName':'school',
                                                          'CohortStudents':'totalenrolled',
                                                          'Dropout (Rate)':'dropout'})

dropout_19['year'] = 2019

dropout_19.to_csv('cali_drop19.csv')

# Year 2018

In [107]:
drop18 = pd.read_csv('drop18.csv')

# re-compute schoolcode to be consistent with other dataset
drop18['SchoolCode'] = drop18['SchoolCode'].astype('str')
for i in range(drop18.shape[0]):
    code_len = len(drop18.loc[i, 'SchoolCode'])
    if code_len != 7:
        add_len = 7 - code_len
        add_str = '0' * add_len
        drop18.loc[i, 'SchoolCode'] = add_str + drop18.loc[i, 'SchoolCode']


drop18[['CountyCode','DistrictCode','SchoolCode']] = drop18[['CountyCode','DistrictCode',
                                                             'SchoolCode']].astype('str')

drop18['cdc_code'] = drop18['CountyCode'] + drop18['DistrictCode'] + drop18['SchoolCode']

# remove rows with no dropout data
drop18 = drop18.loc[drop18['Dropout (Rate)'] != '*']
drop18 = drop18.drop(columns = ['AcademicYear', 'AggregateLevel'])
dropout18 = drop18.loc[drop18['ReportingCategory'] == 'TA'].drop(columns = ['ReportingCategory', 
                                                                            'Dropout (Count)'])

In [108]:
demo18 = drop18.loc[:, ['cdc_code', 'ReportingCategory', 'CohortStudents']].pivot(index = 'cdc_code', 
                    columns = 'ReportingCategory', values = 'CohortStudents').fillna(0).reset_index()

demo18 = demo18.loc[:, ['cdc_code', 'RW', 'RB', 'RH', 'SS', 'TA']]
demo18.loc[:, ['RW', 'RB', 'RH', 'SS', 'TA']] = demo18.loc[:, ['RW', 'RB', 'RH', 'SS', 'TA']].astype('int')

demo18['white'] = demo18['RW'] / demo18['TA']
demo18['black'] = demo18['RB'] / demo18['TA']
demo18['hispanic'] = demo18['RH'] / demo18['TA']
demo18['lowincome'] = demo18['SS'] / demo18['TA']

demo18 = demo18.loc[:, ['cdc_code', 'white', 'black', 'hispanic', 'lowincome']]

demo18['white'] = demo18.white.astype('float')
demo18['black'] = demo18.black.astype('float')
demo18['hispanic'] = demo18.hispanic.astype('float')
demo18['lowincome'] = demo18.lowincome.astype('float')

dropout_18 = demo18.merge(dropout18, on = 'cdc_code').rename(columns = {'CountyCode':'countycode', 'DistrictCode':
                                                          'districtcode', 'SchoolCode':'schoolcode',
                                                           'CountyName':'county',
                                                          'DistrictName':'district', 'SchoolName':'school',
                                                          'CohortStudents':'totalenrolled',
                                                          'Dropout (Rate)':'dropout'})

dropout_18['year'] = 2018

dropout_18.to_csv('cali_drop18.csv')

# Year 2017

In [109]:
drop17 = pd.read_csv('drop17.csv')
# re-compute schoolcode to be consistent with other dataset
drop17['SchoolCode'] = drop17['SchoolCode'].astype('str')
for i in range(drop17.shape[0]):
    code_len = len(drop17.loc[i, 'SchoolCode'])
    if code_len != 7:
        add_len = 7 - code_len
        add_str = '0' * add_len
        drop17.loc[i, 'SchoolCode'] = add_str + drop17.loc[i, 'SchoolCode']

drop17[['CountyCode','DistrictCode','SchoolCode']] = drop17[['CountyCode','DistrictCode',
                                                             'SchoolCode']].astype('str')

drop17['cdc_code'] = drop17['CountyCode'] + drop17['DistrictCode'] + drop17['SchoolCode']

# remove rows with no dropout data
drop17 = drop17.loc[drop17['Dropout (Rate)'] != '*']
drop17 = drop17.drop(columns = ['AcademicYear', 'AggregateLevel'])
dropout17 = drop17.loc[drop17['ReportingCategory'] == 'TA'].drop(columns = ['ReportingCategory', 
                                                                            'Dropout (Count)'])

In [110]:
demo17 = drop17.loc[:, ['cdc_code', 'ReportingCategory', 'CohortStudents']].pivot(index = 'cdc_code', 
                    columns = 'ReportingCategory', values = 'CohortStudents').fillna(0).reset_index()

demo17 = demo17.loc[:, ['cdc_code', 'RW', 'RB', 'RH', 'SS', 'TA']]
demo17.loc[:, ['RW', 'RB', 'RH', 'SS', 'TA']] = demo17.loc[:, ['RW', 'RB', 'RH', 'SS', 'TA']].astype('int')

demo17['white'] = demo17['RW'] / demo17['TA']
demo17['black'] = demo17['RB'] / demo17['TA']
demo17['hispanic'] = demo17['RH'] / demo17['TA']
demo17['lowincome'] = demo17['SS'] / demo17['TA']

demo17 = demo17.loc[:, ['cdc_code', 'white', 'black', 'hispanic', 'lowincome']]

demo17['white'] = demo17.white.astype('float')
demo17['black'] = demo17.black.astype('float')
demo17['hispanic'] = demo17.hispanic.astype('float')
demo17['lowincome'] = demo17.lowincome.astype('float')

dropout_17 = demo17.merge(dropout17, on = 'cdc_code').rename(columns = {'CountyCode':'countycode', 'DistrictCode':
                                                          'districtcode', 'SchoolCode':'schoolcode',
                                                           'CountyName':'county',
                                                          'DistrictName':'district', 'SchoolName':'school',
                                                          'CohortStudents':'totalenrolled',
                                                          'Dropout (Rate)':'dropout'})

dropout_17['year'] = 2017

dropout_17.to_csv('cali_drop17.csv')

# Year 2016

In [23]:
drop16 = pd.read_csv('drop16.csv')

total = drop16.groupby('cdc_code').sum().reset_index().loc[:, ['cdc_code', 'totalenrolled', 'drop (count)']]
total = total.loc[total['totalenrolled'] != 0]
total['dropout'] = total['drop (count)'] / total['totalenrolled']

total = total.loc[:, ['cdc_code', 'totalenrolled', 'dropout']]

race = drop16.groupby(['cdc_code', 'ethnic']).sum().reset_index().pivot(index = 'cdc_code', columns = 'ethnic',
values = 'totalenrolled').reset_index().fillna(0).loc[:, ['cdc_code', 5, 6, 7]]

drop16 = race.merge(total, on = 'cdc_code')
drop16['white'] = drop16[7] / drop16['totalenrolled']
drop16['black'] = drop16[6] / drop16['totalenrolled']
drop16['hispanic'] = drop16[5] / drop16['totalenrolled']

drop16 = drop16.drop(columns = [5, 6, 7])

drop16['cdc_code'] = drop16['cdc_code'].astype('str')

In [32]:
frpm16 = pd.read_csv('frpm16.csv').dropna()
frpm16[['County Code','District School']] = frpm16[['County Code','District School']].astype('str')

frpm16['cdc_code'] = frpm16['County Code'] + frpm16['District School']

dropout16 = frpm16.loc[:, ['charter', 'frpm', 'cdc_code']].merge(drop16, 
    on = 'cdc_code').rename(columns = {'frpm':'lowincome'})

charter_map = {'Y': 1, 'N': 0}

dropout16['charter'] = dropout16['charter'].map(charter_map)

dropout16['year'] = 2016

dropout16.to_csv('cali_drop16.csv')

# Year 2015

In [3]:
drop15 = pd.read_csv('drop15.csv')

total = drop15.groupby('cdc_code').sum().reset_index().loc[:, ['cdc_code', 'totalenrolled', 'drop (count)']]
total = total.loc[total['totalenrolled'] != 0]
total['dropout'] = total['drop (count)'] / total['totalenrolled']

total = total.loc[:, ['cdc_code', 'totalenrolled', 'dropout']]

race = drop15.groupby(['cdc_code', 'ethnic']).sum().reset_index().pivot(index = 'cdc_code', columns = 'ethnic',
values = 'totalenrolled').reset_index().fillna(0).loc[:, ['cdc_code', 5, 6, 7]]

drop15 = race.merge(total, on = 'cdc_code')
drop15['white'] = drop15[7] / drop15['totalenrolled']
drop15['black'] = drop15[6] / drop15['totalenrolled']
drop15['hispanic'] = drop15[5] / drop15['totalenrolled']

drop15 = drop15.drop(columns = [5, 6, 7])

drop15['cdc_code'] = drop15['cdc_code'].astype('str')

In [31]:
frpm15 = pd.read_csv('frpm15.csv').dropna()
frpm15['cdc_code'] = frpm15['cdc_code'].astype('int').astype('str')

dropout15 = frpm15.loc[:, ['charter', 'frpm', 'cdc_code']].merge(drop15, 
    on = 'cdc_code').rename(columns = {'frpm':'lowincome'})

charter_map = {'Y': 1, 'N': 0}

dropout15['charter'] = dropout15['charter'].map(charter_map)

dropout15['year'] = 2015

dropout15.to_csv('cali_drop15.csv')

# Merge six years of drop-out data

In [140]:
d15 = pd.read_csv('cali_drop15.csv').iloc[:, 1:]
d16 = pd.read_csv('cali_drop16.csv').iloc[:, 1:]
d17 = pd.read_csv('cali_drop17.csv').iloc[:, 1:]
d18 = pd.read_csv('cali_drop18.csv').iloc[:, 1:]
d19 = pd.read_csv('cali_drop19.csv').iloc[:, 1:]
d21 = pd.read_csv('cali_drop21.csv').iloc[:, 1:]

mutual_cdc = list(set(d21.cdc_code).intersection(set(d19.cdc_code)).intersection(
    set(d18.cdc_code)).intersection(set(d17.cdc_code)).intersection(set(d16.cdc_code)).intersection(
    set(d15.cdc_code)))

d15 = d15.set_index('cdc_code').loc[mutual_cdc, :].reset_index()
d16 = d16.set_index('cdc_code').loc[mutual_cdc, :].reset_index()
d17 = d17.set_index('cdc_code').loc[mutual_cdc, :].reset_index()
d18 = d18.set_index('cdc_code').loc[mutual_cdc, :].reset_index()
d19 = d19.set_index('cdc_code').loc[mutual_cdc, :].reset_index()
d21 = d21.set_index('cdc_code').loc[mutual_cdc, :].reset_index()

post17 = pd.concat([d17, d18, d19, d21]).loc[:, ['cdc_code','white', 'black', 'hispanic', 
                                                'lowincome','totalenrolled', 'dropout', 'year']].merge(
d15.loc[:, ['cdc_code', 'charter']], on = 'cdc_code'
)

pd.concat([d15, d16, post17]).to_csv('cali_drop_allyear.csv')

# Merge Drop-out with School Mode

In [12]:
import numpy as np

mode = pd.read_csv('schoolmode.csv')[['Charter', 'StateAssignedSchoolID', 'EnrollmentTotal',
                     'TimePeriodStart', 'TimePeriodEnd', 'LearningModel']]

norm_mode = mode.groupby(['StateAssignedSchoolID'])['LearningModel'].value_counts(
    normalize = True).to_frame().rename(columns = {'LearningModel': 'normalized'}).reset_index()
norm_mode.head()

pivot_df = pd.pivot(norm_mode, index = ['StateAssignedSchoolID'], 
         columns = 'LearningModel', values = 'normalized').reset_index()
pivot_df = pivot_df.replace(np.nan, 0)

pivot_df = pivot_df.rename(columns = {'StateAssignedSchoolID':'cdc_code'})

pivot_df.cdc_code = pivot_df.cdc_code.astype('int')

pivot_df.to_csv('cali_schoolmode.csv')

In [79]:
drop_mode = pd.read_csv('cali_schoolmode.csv').iloc[:, 1:].loc[:, ['cdc_code', 'Hybrid', 'Virtual', 
'In-person']].merge(pd.read_csv('cali_drop_allyear.csv').iloc[:, 1:], 
                    on = 'cdc_code').rename(columns = {'Hybrid':'hybridper','Virtual':'virtualper',
                                                      'In-person':'inpersonper'})

drop_mode.loc[drop_mode['year'] != 2021, 'inpersonper'] = 1
drop_mode.loc[drop_mode['year'] != 2021, 'virtualper'] = 0
drop_mode.loc[drop_mode['year'] != 2021, 'hybridper'] = 0

drop_mode['schoolmode'] = drop_mode['hybridper'] * 0.5 + drop_mode['virtualper'] * 1
drop_mode['schoolcode'] = drop_mode['cdc_code'].astype('str') + 'ca'
drop_mode['districtcode'] = drop_mode['schoolcode'].apply(lambda x: x[-14:-9]) + 'ca'
drop_mode['countycode'] = drop_mode['schoolcode'].apply(lambda x: x[:-14]) + 'ca'
drop_mode.loc[:, ['white', 'black', 'hispanic', 'lowincome']] = round(drop_mode.loc[:, ['white', 
            'black', 'hispanic', 'lowincome']] * 100, 2)
drop_mode['dropout'] = round(drop_mode['dropout'], 2)
drop_mode.loc[:, ['hybridper', 'virtualper', 'schoolmode']] = round(
drop_mode.loc[:, ['hybridper', 'virtualper', 'schoolmode']], 4)
drop_mode['state'] = 'ca'

drop_mode = drop_mode.drop(columns = ['cdc_code', 'inpersonper'])

drop_mode.to_csv('final_data_dropout_ca.csv')